import { User, Election, Candidate, Vote, Organization } from './types';

const getDate = (offsetDays: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString().split('T')[0];
};

export const organizations: Organization[] = [
  {
    id: 'uemol',
    slug: 'uemol',
    name: 'Unidad Educativa Manuela Cañizares (UEMOL)',
    code: 'UEM-01',
    logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=160&auto=format&fit=crop&q=60',
    primaryColor: '#005A9C',
    status: 'ACTIVE',
    createdAt: '2025-01-10T08:00:00.000Z',
    updatedAt: '2025-01-10T08:00:00.000Z',
  },
  {
    id: 'galileo',
    slug: 'galileo',
    name: 'Unidad Educativa Galileo Galilei',
    code: 'GG-02',
    logoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=160&auto=format&fit=crop&q=60',
    primaryColor: '#8B0000',
    status: 'ACTIVE',
    createdAt: '2025-02-01T09:30:00.000Z',
    updatedAt: '2025-02-01T09:30:00.000Z',
  },
  {
    id: 'san-jose',
    slug: 'san-jose',
    name: 'Colegio Experimental San José',
    code: 'CSJ-03',
    logoUrl: null,
    primaryColor: '#1e7b4f',
    status: 'INACTIVE',
    createdAt: '2025-03-15T10:00:00.000Z',
    updatedAt: '2025-03-15T10:00:00.000Z',
  }
];

export const users: User[] = [
  // 1. GLOBAL SUPERADMIN
  {
    id: 'usr_superadmin',
    username: 'superadmin',
    codigo: 'superadmin',
    name: 'Superadministrador Global SIVES',
    email: 'superadmin@sives.edu.ec',
    password: 'password123',
    role: 'SUPERADMIN',
    rol: 'Superadmin',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Admin',
    primer_apellido: 'Global',
    curso: 'N/A',
    paralelo: 'N/A',
  },

  // 2. ORG ADMINS
  {
    id: 'usr_admin_uemol',
    organizationId: 'uemol',
    username: 'admin_uemol',
    codigo: 'admin',
    name: 'Ing. Marco Lema (Admin UEMOL)',
    email: 'admin.uemol@sives.edu.ec',
    password: 'password123',
    role: 'ADMIN',
    rol: 'Admin',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Marco',
    segundo_nombre: 'Antonio',
    primer_apellido: 'Lema',
    segundo_apellido: 'Pérez',
    curso: 'Administración',
    paralelo: 'Central',
  },
  {
    id: 'usr_admin_galileo',
    organizationId: 'galileo',
    username: 'admin_galileo',
    codigo: 'admin_gg',
    name: 'Dra. Susana Guerra (Admin Galileo)',
    email: 'directora.gg@sives.edu.ec',
    password: 'password123',
    role: 'ADMIN',
    rol: 'Admin',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Susana',
    segundo_nombre: 'Beatriz',
    primer_apellido: 'Guerra',
    segundo_apellido: 'Maldonado',
    curso: 'Dirección',
    paralelo: 'General',
  },
  {
    id: 'usr_admin_sanjose',
    organizationId: 'san-jose',
    username: 'admin_sanjose',
    codigo: 'admin_sj',
    name: 'Lic. Carlos Benítez (Admin San José)',
    email: 'rector.csj@sives.edu.ec',
    password: 'password123',
    role: 'ADMIN',
    rol: 'Admin',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Carlos',
    primer_apellido: 'Benítez',
    curso: 'Rectorado',
    paralelo: 'A',
  },

  // 3. STUDENTS - UEMOL
  {
    id: 'usr_uemol_1',
    organizationId: 'uemol',
    studentCode: '2025001',
    codigo: '2025001',
    name: 'Ana María García López',
    role: 'STUDENT',
    rol: 'Estudiante',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Ana',
    segundo_nombre: 'María',
    primer_apellido: 'García',
    segundo_apellido: 'López',
    curso: 'Décimo EGB',
    paralelo: 'A',
    email: 'ana.garcia@estudiantes.uemol.edu.ec',
  },
  {
    id: 'usr_uemol_2',
    organizationId: 'uemol',
    studentCode: '2025002',
    codigo: '2025002',
    name: 'Luis Alberto Pérez Rodríguez',
    role: 'STUDENT',
    rol: 'Estudiante',
    ha_votado: ['elec_uemol_1'],
    hasVoted: { 'elec_uemol_1': true },
    primer_nombre: 'Luis',
    segundo_nombre: 'Alberto',
    primer_apellido: 'Pérez',
    segundo_apellido: 'Rodríguez',
    curso: 'Décimo EGB',
    paralelo: 'B',
    email: 'luis.perez@estudiantes.uemol.edu.ec',
  },
  {
    id: 'usr_uemol_3',
    organizationId: 'uemol',
    studentCode: '2025003',
    codigo: '2025003',
    name: 'María Fernanda Rodríguez Sánchez',
    role: 'STUDENT',
    rol: 'Estudiante',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'María',
    segundo_nombre: 'Fernanda',
    primer_apellido: 'Rodríguez',
    segundo_apellido: 'Sánchez',
    curso: 'Noveno EGB',
    paralelo: 'A',
  },
  {
    id: 'usr_uemol_4',
    organizationId: 'uemol',
    studentCode: '2025004',
    codigo: '2025004',
    name: 'Carlos Eduardo Sánchez Martínez',
    role: 'STUDENT',
    rol: 'Estudiante',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Carlos',
    segundo_nombre: 'Eduardo',
    primer_apellido: 'Sánchez',
    segundo_apellido: 'Martínez',
    curso: 'Onceavo Grado',
    paralelo: 'C',
  },
  {
    id: 'usr_uemol_5',
    organizationId: 'uemol',
    studentCode: '2025005',
    codigo: '2025005',
    name: 'Sofía Valentina López Hernández',
    role: 'STUDENT',
    rol: 'Estudiante',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Sofía',
    segundo_nombre: 'Valentina',
    primer_apellido: 'López',
    segundo_apellido: 'Hernández',
    curso: 'Onceavo Grado',
    paralelo: 'C',
  },

  // 4. STUDENTS - GALILEO
  {
    id: 'usr_galileo_1',
    organizationId: 'galileo',
    studentCode: 'GG2401',
    codigo: 'GG2401',
    name: 'David Benavidez Cortés',
    role: 'STUDENT',
    rol: 'Estudiante',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'David',
    primer_apellido: 'Benavidez',
    segundo_apellido: 'Cortés',
    curso: '1ero BGU',
    paralelo: 'A',
    email: 'david.b@galileo.edu.ec',
  },
  {
    id: 'usr_galileo_2',
    organizationId: 'galileo',
    studentCode: 'GG2402',
    codigo: 'GG2402',
    name: 'Elena Isabel Vargas Mora',
    role: 'STUDENT',
    rol: 'Estudiante',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Elena',
    segundo_nombre: 'Isabel',
    primer_apellido: 'Vargas',
    segundo_apellido: 'Mora',
    curso: '2do BGU',
    paralelo: 'B',
  },
  {
    id: 'usr_galileo_3',
    organizationId: 'galileo',
    studentCode: 'GG2403',
    codigo: 'GG2403',
    name: 'Mateo Alejandro Ríos Castro',
    role: 'STUDENT',
    rol: 'Estudiante',
    ha_votado: [],
    hasVoted: {},
    primer_nombre: 'Mateo',
    segundo_nombre: 'Alejandro',
    primer_apellido: 'Ríos',
    segundo_apellido: 'Castro',
    curso: '3ero BGU',
    paralelo: 'A',
  }
];

export const elections: Election[] = [
  // UEMOL Elections
  {
    id: 'elec_uemol_1',
    organizationId: 'uemol',
    title: 'Elección de Presidente Estudiantil 2025',
    description: 'Elección democrática anual para presidir el Consejo Estudiantil UEMOL.',
    startDate: getDate(-2),
    endDate: getDate(2),
    status: 'ACTIVE',
    allowBlank: true,
    allowWriteIn: true,
    nombre: 'Elección de Presidente Estudiantil 2025',
    fecha_inicio: getDate(-2),
    fecha_fin: getDate(2),
    estado: 'Activa',
    resultados_publicos: false,
    descripcion: 'Elección democrática anual para presidir el Consejo Estudiantil UEMOL.',
  },
  {
    id: 'elec_uemol_2',
    organizationId: 'uemol',
    title: 'Representante al Consejo Consultivo',
    description: 'Votación para elegir el delegado estudiantil ante las autoridades de la institución.',
    startDate: getDate(-1),
    endDate: getDate(3),
    status: 'ACTIVE',
    allowBlank: true,
    allowWriteIn: false,
    nombre: 'Representante al Consejo Consultivo',
    fecha_inicio: getDate(-1),
    fecha_fin: getDate(3),
    estado: 'Activa',
    resultados_publicos: false,
    descripcion: 'Votación para elegir el delegado estudiantil ante las autoridades de la institución.',
  },
  {
    id: 'elec_uemol_3',
    organizationId: 'uemol',
    title: 'Referéndum Mascota Institucional',
    description: 'Consulta estudiantil sobre adopción de mascota representativa del plantel.',
    startDate: getDate(-15),
    endDate: getDate(-5),
    status: 'CLOSED',
    allowBlank: true,
    allowWriteIn: false,
    nombre: 'Referéndum Mascota Institucional',
    fecha_inicio: getDate(-15),
    fecha_fin: getDate(-5),
    estado: 'Cerrada',
    resultados_publicos: true,
    descripcion: 'Consulta estudiantil sobre adopción de mascota representativa del plantel.',
  },

  // Galileo Elections
  {
    id: 'elec_galileo_1',
    organizationId: 'galileo',
    title: 'Consejo Estudiantil Galileo 2025-2026',
    description: 'Elección general de directiva del Consejo Estudiantil Galileo Galilei.',
    startDate: getDate(-1),
    endDate: getDate(5),
    status: 'ACTIVE',
    allowBlank: true,
    allowWriteIn: true,
    nombre: 'Consejo Estudiantil Galileo 2025-2026',
    fecha_inicio: getDate(-1),
    fecha_fin: getDate(5),
    estado: 'Activa',
    resultados_publicos: true,
    descripcion: 'Elección general de directiva del Consejo Estudiantil Galileo Galilei.',
  },
  {
    id: 'elec_galileo_2',
    organizationId: 'galileo',
    title: 'Comité de Deportes y Recreación',
    description: 'Representantes estudiantiles para la organización de olimpiadas y torneos escolares.',
    startDate: getDate(-20),
    endDate: getDate(-10),
    status: 'CLOSED',
    allowBlank: true,
    allowWriteIn: false,
    nombre: 'Comité de Deportes y Recreación',
    fecha_inicio: getDate(-20),
    fecha_fin: getDate(-10),
    estado: 'Cerrada',
    resultados_publicos: true,
    descripcion: 'Representantes estudiantiles para la organización de olimpiadas y torneos escolares.',
  }
];

export const candidates: Candidate[] = [
  // Elec 1 - UEMOL
  {
    id: 'cand_uemol_1',
    electionId: 'elec_uemol_1',
    eleccion_id: 'elec_uemol_1',
    organizationId: 'uemol',
    name: 'Juan Carlos Gómez',
    nombres: 'Juan Carlos',
    apellido: 'Gómez',
    party: 'Lista 1 - Innovación y Futuro',
    partido_politico: 'Lista 1 - Innovación y Futuro',
    platform: 'Mejora en salas de cómputo, torneos intercolegiales y talleres extracurriculares de liderazgo.',
    cargo: 'Presidente',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    foto_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    descripcion: 'Mejora en salas de cómputo, torneos intercolegiales y talleres extracurriculares de liderazgo.',
    color: '#005A9C',
  },
  {
    id: 'cand_uemol_2',
    electionId: 'elec_uemol_1',
    eleccion_id: 'elec_uemol_1',
    organizationId: 'uemol',
    name: 'Laura Sofía Martínez',
    nombres: 'Laura Sofía',
    apellido: 'Martínez',
    party: 'Lista 2 - Frente Unido Estudiantil',
    partido_politico: 'Lista 2 - Frente Unido Estudiantil',
    platform: 'Tutorías académicas entre pares, áreas de descanso sostenibles y reciclaje institucional.',
    cargo: 'Presidente',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    foto_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    descripcion: 'Tutorías académicas entre pares, áreas de descanso sostenibles y reciclaje institucional.',
    color: '#FDB813',
  },

  // Elec 2 - UEMOL
  {
    id: 'cand_uemol_3',
    electionId: 'elec_uemol_2',
    eleccion_id: 'elec_uemol_2',
    organizationId: 'uemol',
    name: 'Pedro Díaz Alarcón',
    nombres: 'Pedro',
    apellido: 'Díaz',
    party: 'Alianza Pro-Grado',
    partido_politico: 'Alianza Pro-Grado',
    platform: 'Canal directo de comunicación entre estudiantes y directivos para resolver inquietudes.',
    cargo: 'Representante',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    foto_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    descripcion: 'Canal directo de comunicación entre estudiantes y directivos para resolver inquietudes.',
  },
  {
    id: 'cand_uemol_4',
    electionId: 'elec_uemol_2',
    eleccion_id: 'elec_uemol_2',
    organizationId: 'uemol',
    name: 'Isabel Castillo',
    nombres: 'Isabel',
    apellido: 'Castillo',
    party: 'Movimiento Voces Jóvenes',
    partido_politico: 'Movimiento Voces Jóvenes',
    platform: 'Promoción del arte y la música en las semanas culturales colegiales.',
    cargo: 'Representante',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    foto_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    descripcion: 'Promoción del arte y la música en las semanas culturales colegiales.',
  },

  // Elec 3 - UEMOL
  {
    id: 'cand_uemol_5',
    electionId: 'elec_uemol_3',
    eleccion_id: 'elec_uemol_3',
    organizationId: 'uemol',
    name: 'Opción Sí (A favor de la mascota)',
    nombres: 'Opción Sí',
    apellido: '',
    party: 'Causa Animalista Escolar',
    partido_politico: 'Causa Animalista Escolar',
    platform: 'Fomentar la empatía y responsabilidad adoptando un perrito comunitario para el colegio.',
    cargo: 'Opción',
    photoUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=200&auto=format&fit=crop&q=80',
    foto_url: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'cand_uemol_6',
    electionId: 'elec_uemol_3',
    eleccion_id: 'elec_uemol_3',
    organizationId: 'uemol',
    name: 'Opción No',
    nombres: 'Opción No',
    apellido: '',
    party: 'Enfoque en Infraestructura',
    partido_politico: 'Enfoque en Infraestructura',
    platform: 'Priorizar fondos en laboratorios de ciencias antes de asumir cuidados veterinarios.',
    cargo: 'Opción',
    photoUrl: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=200&auto=format&fit=crop&q=80',
    foto_url: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=200&auto=format&fit=crop&q=80',
  },

  // Elec 4 - Galileo
  {
    id: 'cand_galileo_1',
    electionId: 'elec_galileo_1',
    eleccion_id: 'elec_galileo_1',
    organizationId: 'galileo',
    name: 'Lista A - Progreso Estudiantil',
    nombres: 'Lista A',
    apellido: 'Progreso',
    party: 'Progreso Estudiantil Galileo',
    partido_politico: 'Progreso Estudiantil Galileo',
    platform: 'Club de robótica y programación, biblioteca virtual accesible las 24 horas y ferias científicas.',
    cargo: 'Directiva Consejo',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    foto_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    color: '#8B0000',
  },
  {
    id: 'cand_galileo_2',
    electionId: 'elec_galileo_1',
    eleccion_id: 'elec_galileo_1',
    organizationId: 'galileo',
    name: 'Lista B - Fuerza Unida',
    nombres: 'Lista B',
    apellido: 'Unidad',
    party: 'Fuerza Unida Galileo',
    partido_politico: 'Fuerza Unida Galileo',
    platform: 'Fomento a las artes, radio escolar comunitaria y mejoras en canchas deportivas multiuso.',
    cargo: 'Directiva Consejo',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    foto_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    color: '#005A9C',
  }
];

export const votes: Vote[] = [
  // UEMOL Vote
  {
    id: 'vote_1',
    organizationId: 'uemol',
    eleccion_id: 'elec_uemol_1',
    electionId: 'elec_uemol_1',
    user_id: 'usr_uemol_2',
    voterId: 'usr_uemol_2',
    candidato_id: 'cand_uemol_1',
    candidateId: 'cand_uemol_1',
    fecha_voto: '2025-02-10T14:32:00.000Z',
    timestamp: '2025-02-10T14:32:00.000Z',
    receipt: 'rcpt-elec_uemol_1-usr_uemol_2-a8f9b2',
  },
  {
    id: 'vote_2',
    organizationId: 'uemol',
    eleccion_id: 'elec_uemol_3',
    electionId: 'elec_uemol_3',
    user_id: 'usr_uemol_1',
    voterId: 'usr_uemol_1',
    candidato_id: 'cand_uemol_5',
    candidateId: 'cand_uemol_5',
    fecha_voto: '2025-02-01T10:15:00.000Z',
    timestamp: '2025-02-01T10:15:00.000Z',
    receipt: 'rcpt-elec_uemol_3-usr_uemol_1-c4d7e1',
  },
  {
    id: 'vote_3',
    organizationId: 'uemol',
    eleccion_id: 'elec_uemol_3',
    electionId: 'elec_uemol_3',
    user_id: 'usr_uemol_2',
    voterId: 'usr_uemol_2',
    candidato_id: 'cand_uemol_5',
    candidateId: 'cand_uemol_5',
    fecha_voto: '2025-02-01T11:20:00.000Z',
    timestamp: '2025-02-01T11:20:00.000Z',
    receipt: 'rcpt-elec_uemol_3-usr_uemol_2-f9e2d3',
  },
  {
    id: 'vote_4',
    organizationId: 'uemol',
    eleccion_id: 'elec_uemol_3',
    electionId: 'elec_uemol_3',
    user_id: 'usr_uemol_3',
    voterId: 'usr_uemol_3',
    candidato_id: 'cand_uemol_6',
    candidateId: 'cand_uemol_6',
    fecha_voto: '2025-02-02T09:45:00.000Z',
    timestamp: '2025-02-02T09:45:00.000Z',
    receipt: 'rcpt-elec_uemol_3-usr_uemol_3-1b7a9c',
  }
];
